### ISSUE TITLE
Error calculating costs with Tibber provider

### ISSUE THREAD

**Issue by JonasF1** [MattJeanes/TeslaMateAgile#33]
Hi,
Have used this excellent app with my Teslamate installation. 
But now it does not work anymore. Stopped working 3-4 weeks ago.
Get following error on my docker instants  when using the Tibber provider.

```
teslamateagile_1  | dbug: TeslaMateAgile.PriceService[0]
teslamateagile_1  |       Updating prices
teslamateagile_1  | info: TeslaMateAgile.PriceHelper[0]
teslamateagile_1  |       Looking for finished charging processes with no cost set in the 'Garaget' geofence (id: 1)
teslamateagile_1  | info: TeslaMateAgile.PriceHelper[0]
teslamateagile_1  |       Calculating cost for charges 10/28/2022 19:30:04 UTC - 10/28/2022 19:30:10 UTC
teslamateagile_1  | fail: TeslaMateAgile.PriceHelper[0]
teslamateagile_1  |       Failed to calculate charging cost / energy for charging process 1287
teslamateagile_1  |       System.NullReferenceException: Object reference not set to an instance of an object.
teslamateagile_1  |          at TeslaMateAgile.Services.TibberService.GetPriceData(DateTimeOffset from, DateTimeOffset to) in /src/TeslaMateAgile/Services/TibberService.cs:line 68
teslamateagile_1  |          at TeslaMateAgile.PriceHelper.CalculateChargeCost(IEnumerable`1 charges) in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 86
teslamateagile_1  |          at TeslaMateAgile.PriceHelper.Update() in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 64
teslamateagile_1  | info: TeslaMateAgile.PriceHelper[0]
teslamateagile_1  |       Calculating cost for charges 11/21/2022 01:23:31 UTC - 11/21/2022 03:28:46 UTC
teslamateagile_1  | fail: TeslaMateAgile.PriceHelper[0]
teslamateagile_1  |       Failed to calculate charging cost / energy for charging process 1313
teslamateagile_1  |       System.NullReferenceException: Object reference not set to an instance of an object.
teslamateagile_1  |          at TeslaMateAgile.Services.TibberService.GetPriceData(DateTimeOffset from, DateTimeOffset to) in /src/TeslaMateAgile/Services/TibberService.cs:line 68
teslamateagile_1  |          at TeslaMateAgile.PriceHelper.CalculateChargeCost(IEnumerable`1 charges) in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 86
teslamateagile_1  |          at TeslaMateAgile.PriceHelper.Update() in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 64
```

**Comment by MattJeanes** [comment]
Hi, I'm seeing the same thing on my end for any call to Tibber's API for all requests right now so I am guessing either they've changed the API without documenting it or they're having some issues right now.  I'd recommend contacting their support for more information. You can tell them that the `Data.Viewer.Homes[0].CurrentSubscription` is null in their GraphQL API response which may help them.

**Comment by MattJeanes** [comment]
Fantastic to hear! Thanks, I'll close this off then 🙂
