### ISSUE TITLE
Issue with Tibber service

### ISSUE THREAD

**Issue by hentvanoijen** [MattJeanes/TeslaMateAgile#62]
Hi,
I have succesfully configured the tibber service but it is throwing me the following exception. Cannot figure out what is going wrong. Any clue?

---------

fail: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:49:20 teslamateagile-1  |       Failed to calculate charging cost / energy for charging process 1
2024-08-07 21:49:20 teslamateagile-1  |       System.Exception: Mismatch of requested price info from Tibber API (expected: 2, actual: 0)
2024-08-07 21:49:20 teslamateagile-1  |          at TeslaMateAgile.Services.TibberService.GetPriceData(DateTimeOffset from, DateTimeOffset to) in /src/TeslaMateAgile/Services/TibberService.cs:line 122
2024-08-07 21:49:20 teslamateagile-1  |          at TeslaMateAgile.PriceHelper.CalculateChargeCost(IEnumerable`1 charges) in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 96
2024-08-07 21:49:20 teslamateagile-1  |          at TeslaMateAgile.PriceHelper.Update() in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 74

**Comment by MattJeanes** [comment]
Can you enable the debug logging [as mentioned here](https://github.com/MattJeanes/TeslaMateAgile#optional-environment-variables) and see what it says?

**Comment by hentvanoijen** [comment]
Hi Matt,

it seems that after a few hours the actual costs are calculated but there is a constant message about a mismatch. Below a full debug log:

-----

teslamateagile-1  | info: TeslaMateAgile.PriceService[0]
2024-08-07 21:44:20 teslamateagile-1  |       Price service is starting
2024-08-07 21:44:20 teslamateagile-1  | info: TeslaMateAgile.PriceService[0]
2024-08-07 21:44:20 teslamateagile-1  |       Using energy provider Tibber
2024-08-07 21:44:20 teslamateagile-1  | info: Microsoft.Hosting.Lifetime[0]
2024-08-07 21:44:20 teslamateagile-1  |       Application started. Press Ctrl+C to shut down.
2024-08-07 21:44:20 teslamateagile-1  | info: Microsoft.Hosting.Lifetime[0]
2024-08-07 21:44:20 teslamateagile-1  |       Hosting environment: Production
2024-08-07 21:44:20 teslamateagile-1  | info: Microsoft.Hosting.Lifetime[0]
2024-08-07 21:44:20 teslamateagile-1  |       Content root path: /app/
2024-08-07 21:44:20 teslamateagile-1  | dbug: TeslaMateAgile.PriceService[0]
2024-08-07 21:44:20 teslamateagile-1  |       Updating prices
2024-08-07 21:44:20 teslamateagile-1  | info: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:44:20 teslamateagile-1  |       Looking for finished charging processes with no cost set in the 'Thuis' geofence (id: 1)
2024-08-07 21:44:20 teslamateagile-1  | info: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:44:20 teslamateagile-1  |       Calculating cost for charges 08/07/2024 19:09:35 UTC - 08/07/2024 19:13:44 UTC
2024-08-07 21:44:21 teslamateagile-1  | fail: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:44:21 teslamateagile-1  |       Failed to calculate charging cost / energy for charging process 1
2024-08-07 21:44:21 teslamateagile-1  |       System.Exception: Mismatch of requested price info from Tibber API (expected: 2, actual: 0)
2024-08-07 21:44:21 teslamateagile-1  |          at TeslaMateAgile.Services.TibberService.GetPriceData(DateTimeOffset from, DateTimeOffset to) in /src/TeslaMateAgile/Services/TibberService.cs:line 122
2024-08-07 21:44:21 teslamateagile-1  |          at TeslaMateAgile.PriceHelper.CalculateChargeCost(IEnumerable`1 charges) in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 96
2024-08-07 21:44:21 teslamateagile-1  |          at TeslaMateAgile.PriceHelper.Update() in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 74
2024-08-07 21:44:21 teslamateagile-1  | info: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:44:21 teslamateagile-1  |       Calculating cost for charges 08/07/2024 19:14:11 UTC - 08/07/2024 19:17:59 UTC
2024-08-07 21:44:21 teslamateagile-1  | fail: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:44:21 teslamateagile-1  |       Failed to calculate charging cost / energy for charging process 2
2024-08-07 21:44:21 teslamateagile-1  |       System.Exception: Mismatch of requested price info from Tibber API (expected: 2, actual: 0)
2024-08-07 21:44:21 teslamateagile-1  |          at TeslaMateAgile.Services.TibberService.GetPriceData(DateTimeOffset from, DateTimeOffset to) in /src/TeslaMateAgile/Services/TibberService.cs:line 122
2024-08-07 21:44:21 teslamateagile-1  |          at TeslaMateAgile.PriceHelper.CalculateChargeCost(IEnumerable`1 charges) in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 96
2024-08-07 21:44:21 teslamateagile-1  |          at TeslaMateAgile.PriceHelper.Update() in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 74
2024-08-07 21:44:21 teslamateagile-1  | dbug: TeslaMateAgile.PriceService[0]
2024-08-07 21:44:21 teslamateagile-1  |       Price update complete
2024-08-07 21:44:21 teslamateagile-1  | info: TeslaMateAgile.PriceService[0]
2024-08-07 21:44:21 teslamateagile-1  |       Waiting 300 seconds until next update
2024-08-07 21:49:20 teslamateagile-1  | dbug: TeslaMateAgile.PriceService[0]
2024-08-07 21:49:20 teslamateagile-1  |       Updating prices
2024-08-07 21:49:20 teslamateagile-1  | info: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:49:20 teslamateagile-1  |       Looking for finished charging processes with no cost set in the 'Thuis' geofence (id: 1)
2024-08-07 21:49:20 teslamateagile-1  | info: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:49:20 teslamateagile-1  |       Calculating cost for charges 08/07/2024 19:09:35 UTC - 08/07/2024 19:13:44 UTC
2024-08-07 21:49:20 teslamateagile-1  | fail: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:49:20 teslamateagile-1  |       Failed to calculate charging cost / energy for charging process 1
2024-08-07 21:49:20 teslamateagile-1  |       System.Exception: Mismatch of requested price info from Tibber API (expected: 2, actual: 0)
2024-08-07 21:49:20 teslamateagile-1  |          at TeslaMateAgile.Services.TibberService.GetPriceData(DateTimeOffset from, DateTimeOffset to) in /src/TeslaMateAgile/Services/TibberService.cs:line 122
2024-08-07 21:49:20 teslamateagile-1  |          at TeslaMateAgile.PriceHelper.CalculateChargeCost(IEnumerable`1 charges) in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 96
2024-08-07 21:49:20 teslamateagile-1  |          at TeslaMateAgile.PriceHelper.Update() in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 74
2024-08-07 21:49:20 teslamateagile-1  | info: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:49:20 teslamateagile-1  |       Calculating cost for charges 08/07/2024 19:14:11 UTC - 08/07/2024 19:17:59 UTC
2024-08-07 21:49:20 teslamateagile-1  | fail: TeslaMateAgile.PriceHelper[0]
2024-08-07 21:49:20 teslamateagile-1  |       Failed to calculate charging cost / energy for charging process 2
2024-08-07 21:49:20 teslamateagile-1  |       System.Exception: Mismatch of requested price info from Tibber API (expected: 2, actual: 0)
2024-08-07 21:49:20 teslamateagile-1  |          at TeslaMateAgile.Services.TibberService.GetPriceData(DateTimeOffset from, DateTimeOffset to) in /src/TeslaMateAgile/Services/TibberService.cs:line 122
2024-08-07 21:49:20 teslamateagile-1  |          at TeslaMateAgile.PriceHelper.CalculateChargeCost(IEnumerable`1 charges) in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 96
2024-08-07 21:49:20 teslamateagile-1  |          at TeslaMateAgile.PriceHelper.Update() in /src/TeslaMateAgile/Helpers/PriceHelper.cs:line 74
2024-08-07 21:49:20 teslamateagile-1  | dbug: TeslaMateAgile.PriceService[0]
2024-08-07 21:49:20 teslamateagile-1  |       Price update complete
2024-08-07 21:49:20 teslamateagile-1  | info: TeslaMateAgile.PriceService[0]
2024-08-07 21:49:20 teslamateagile-1  |       Waiting 300 seconds until next update

**Comment by MattJeanes** [comment]
Also note that someone else had a very similar issue and this was what they found out from Tibber support, it may be useful to you: https://github.com/MattJeanes/TeslaMateAgile/issues/57#issuecomment-2137207631

**Comment by hentvanoijen** [comment]
Hi Matt,

it seems that the API is returning a result:

`{
  "data": {
    "viewer": {
      "homes": [
        {
          "id": "be849952-e2c6-4a25-a14c-e097bf2651c2",
          "currentSubscription": {
            "priceInfo": {
              "range": {
                "nodes": [
                  {
                    "total": 0.3189,
                    "startsAt": "2024-08-07T21:00:00.000+02:00"
                  },
                  {
                    "total": 0.2929,
                    "startsAt": "2024-08-07T22:00:00.000+02:00"
                  }
                ]
              },
              "current": {
                "total": 0.3015,
                "startsAt": "2024-08-09T22:00:00.000+02:00",
                "level": "EXPENSIVE"
              }
            }
          }
        }
      ]
    }
  }
}`

**Comment by MattJeanes** [comment]
Interesting! The dates look okay to me, they are +02:00 so they are really 19:00 and 20:00 in UTC which is what the query is asking for.

If you're getting a response from the API with your personal token, can you double check it's set correctly in TeslaMateAgile settings? It may also have started working now if that is returning a result, so check your logs as well.

**Comment by hentvanoijen** [comment]
Hi Matt, the issue has been resolved by a restart of my server. I think that was something off with the time. Not sure how that happened...
Thanks for your support!

**Comment by MattJeanes** [comment]
That's odd, but glad to know it's working now! Thanks for letting me know, it's useful if others run into similar issues in the future 🙂
